/**
 * /data.mill for applications
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market. 
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DatamillForApplications) {
      root.DatamillForApplications = {};
    }
    root.DatamillForApplications.UrlCheckResponse = factory(root.DatamillForApplications.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UrlCheckResponse model module.
   * @module model/UrlCheckResponse
   * @version 1.6.4
   */

  /**
   * Constructs a new <code>UrlCheckResponse</code>.
   * Response of successful transformation request for /url/check
   * @alias module:model/UrlCheckResponse
   * @class
   * @param valid {module:model/UrlCheckResponse.ValidEnum} Flag if the root resource (website) is valid or not [0, 1]
   * @param url {String} The final url of the resource
   * @param httpCode {Number} The HTTP status code according to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
   * @param totalTime {Number} Total time of the request in seconds
   * @param namelookupTime {Number} Time until host name resolved in seconds
   * @param connectTime {Number} Time until connection established in seconds
   * @param pretransferTime {Number} Time until file transfer began in seconds
   * @param starttransferTime {Number} Time to first byte in seconds
   * @param primaryIp {String} IP address of the most recent connection
   * @param primaryPort {Number} Destination port of the connection
   * @param downloadContentLength {Number} Number of bytes to download from the resource (-1 means no information available)
   * @param contentType {String} Content type of the requested resource
   * @param redirects {Array.<Object>} Array collection of all urls including redirects
   * @param parameters {Array.<Object>} Array collection of all url parameters
   */
  var exports = function(valid, url, httpCode, totalTime, namelookupTime, connectTime, pretransferTime, starttransferTime, primaryIp, primaryPort, downloadContentLength, contentType, redirects, parameters) {
    var _this = this;

    _this['valid'] = valid;
    _this['url'] = url;
    _this['http_code'] = httpCode;
    _this['total_time'] = totalTime;
    _this['namelookup_time'] = namelookupTime;
    _this['connect_time'] = connectTime;
    _this['pretransfer_time'] = pretransferTime;
    _this['starttransfer_time'] = starttransferTime;
    _this['primary_ip'] = primaryIp;
    _this['primary_port'] = primaryPort;
    _this['download_content_length'] = downloadContentLength;
    _this['content_type'] = contentType;
    _this['redirects'] = redirects;
    _this['parameters'] = parameters;
  };

  /**
   * Constructs a <code>UrlCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UrlCheckResponse} obj Optional instance to populate.
   * @return {module:model/UrlCheckResponse} The populated <code>UrlCheckResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('valid')) {
        obj['valid'] = ApiClient.convertToType(data['valid'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('http_code')) {
        obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
      }
      if (data.hasOwnProperty('total_time')) {
        obj['total_time'] = ApiClient.convertToType(data['total_time'], 'Number');
      }
      if (data.hasOwnProperty('namelookup_time')) {
        obj['namelookup_time'] = ApiClient.convertToType(data['namelookup_time'], 'Number');
      }
      if (data.hasOwnProperty('connect_time')) {
        obj['connect_time'] = ApiClient.convertToType(data['connect_time'], 'Number');
      }
      if (data.hasOwnProperty('pretransfer_time')) {
        obj['pretransfer_time'] = ApiClient.convertToType(data['pretransfer_time'], 'Number');
      }
      if (data.hasOwnProperty('starttransfer_time')) {
        obj['starttransfer_time'] = ApiClient.convertToType(data['starttransfer_time'], 'Number');
      }
      if (data.hasOwnProperty('primary_ip')) {
        obj['primary_ip'] = ApiClient.convertToType(data['primary_ip'], 'String');
      }
      if (data.hasOwnProperty('primary_port')) {
        obj['primary_port'] = ApiClient.convertToType(data['primary_port'], 'Number');
      }
      if (data.hasOwnProperty('download_content_length')) {
        obj['download_content_length'] = ApiClient.convertToType(data['download_content_length'], 'Number');
      }
      if (data.hasOwnProperty('content_type')) {
        obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
      }
      if (data.hasOwnProperty('redirects')) {
        obj['redirects'] = ApiClient.convertToType(data['redirects'], [Object]);
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = ApiClient.convertToType(data['parameters'], [Object]);
      }
    }
    return obj;
  }

  /**
   * Flag if the root resource (website) is valid or not [0, 1]
   * @member {module:model/UrlCheckResponse.ValidEnum} valid
   */
  exports.prototype['valid'] = undefined;
  /**
   * The final url of the resource
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * The HTTP status code according to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
   * @member {Number} http_code
   */
  exports.prototype['http_code'] = undefined;
  /**
   * Total time of the request in seconds
   * @member {Number} total_time
   */
  exports.prototype['total_time'] = undefined;
  /**
   * Time until host name resolved in seconds
   * @member {Number} namelookup_time
   */
  exports.prototype['namelookup_time'] = undefined;
  /**
   * Time until connection established in seconds
   * @member {Number} connect_time
   */
  exports.prototype['connect_time'] = undefined;
  /**
   * Time until file transfer began in seconds
   * @member {Number} pretransfer_time
   */
  exports.prototype['pretransfer_time'] = undefined;
  /**
   * Time to first byte in seconds
   * @member {Number} starttransfer_time
   */
  exports.prototype['starttransfer_time'] = undefined;
  /**
   * IP address of the most recent connection
   * @member {String} primary_ip
   */
  exports.prototype['primary_ip'] = undefined;
  /**
   * Destination port of the connection
   * @member {Number} primary_port
   */
  exports.prototype['primary_port'] = undefined;
  /**
   * Number of bytes to download from the resource (-1 means no information available)
   * @member {Number} download_content_length
   */
  exports.prototype['download_content_length'] = undefined;
  /**
   * Content type of the requested resource
   * @member {String} content_type
   */
  exports.prototype['content_type'] = undefined;
  /**
   * Array collection of all urls including redirects
   * @member {Array.<Object>} redirects
   */
  exports.prototype['redirects'] = undefined;
  /**
   * Array collection of all url parameters
   * @member {Array.<Object>} parameters
   */
  exports.prototype['parameters'] = undefined;


  /**
   * Allowed values for the <code>valid</code> property.
   * @enum {Number}
   * @readonly
   */
  exports.ValidEnum = {
    /**
     * value: 0
     * @const
     */
    "0": 0,
    /**
     * value: 1
     * @const
     */
    "1": 1  };


  return exports;
}));


