/**
 * /data.mill for applications
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market. 
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Datamill/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.datamill-js-client) {
      root.datamill-js-client = {};
    }
    root.datamill-js-client.AddressHouseNumberExtractResponse = factory(root.datamill-js-client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AddressHouseNumberExtractResponse model module.
   * @module Datamill/Datamill/AddressHouseNumberExtractResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>AddressHouseNumberExtractResponse</code>.
   * Response of successful transformation request for /address/housenumber/extract
   * @alias module:Datamill/Datamill/AddressHouseNumberExtractResponse
   * @class
   * @param street {String} The extracted street name
   * @param housenumber {String} House number including additional house number information
   * @param housenumberOnly {String} House number excluding additional house number information
   * @param housenumberAddition {String} Additional house number information
   */
  var exports = function(street, housenumber, housenumberOnly, housenumberAddition) {
    var _this = this;

    _this['street'] = street;
    _this['housenumber'] = housenumber;
    _this['housenumber_only'] = housenumberOnly;
    _this['housenumber_addition'] = housenumberAddition;
  };

  /**
   * Constructs a <code>AddressHouseNumberExtractResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Datamill/Datamill/AddressHouseNumberExtractResponse} obj Optional instance to populate.
   * @return {module:Datamill/Datamill/AddressHouseNumberExtractResponse} The populated <code>AddressHouseNumberExtractResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('housenumber')) {
        obj['housenumber'] = ApiClient.convertToType(data['housenumber'], 'String');
      }
      if (data.hasOwnProperty('housenumber_only')) {
        obj['housenumber_only'] = ApiClient.convertToType(data['housenumber_only'], 'String');
      }
      if (data.hasOwnProperty('housenumber_addition')) {
        obj['housenumber_addition'] = ApiClient.convertToType(data['housenumber_addition'], 'String');
      }
    }
    return obj;
  }

  /**
   * The extracted street name
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * House number including additional house number information
   * @member {String} housenumber
   */
  exports.prototype['housenumber'] = undefined;
  /**
   * House number excluding additional house number information
   * @member {String} housenumber_only
   */
  exports.prototype['housenumber_only'] = undefined;
  /**
   * Additional house number information
   * @member {String} housenumber_addition
   */
  exports.prototype['housenumber_addition'] = undefined;



  return exports;
}));


