/**
 * /data.mill for applications
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market. 
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Datamill/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.datamill-js-client) {
      root.datamill-js-client = {};
    }
    root.datamill-js-client.BusinessDataDunsSearchResult = factory(root.datamill-js-client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BusinessDataDunsSearchResult model module.
   * @module Datamill/Datamill/BusinessDataDunsSearchResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BusinessDataDunsSearchResult</code>.
   * Single item for results array within response of successful transformation request for /business-data/duns/search
   * @alias module:Datamill/Datamill/BusinessDataDunsSearchResult
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>BusinessDataDunsSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Datamill/Datamill/BusinessDataDunsSearchResult} obj Optional instance to populate.
   * @return {module:Datamill/Datamill/BusinessDataDunsSearchResult} The populated <code>BusinessDataDunsSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('company_name')) {
        obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('zip')) {
        obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('house_number')) {
        obj['house_number'] = ApiClient.convertToType(data['house_number'], 'String');
      }
      if (data.hasOwnProperty('duns_number')) {
        obj['duns_number'] = ApiClient.convertToType(data['duns_number'], 'String');
      }
      if (data.hasOwnProperty('duns_number_hq')) {
        obj['duns_number_hq'] = ApiClient.convertToType(data['duns_number_hq'], 'String');
      }
      if (data.hasOwnProperty('phone_number')) {
        obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
      }
      if (data.hasOwnProperty('branch_code')) {
        obj['branch_code'] = ApiClient.convertToType(data['branch_code'], 'String');
      }
      if (data.hasOwnProperty('branch_description')) {
        obj['branch_description'] = ApiClient.convertToType(data['branch_description'], 'String');
      }
      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The official company name
   * @member {String} company_name
   */
  exports.prototype['company_name'] = undefined;
  /**
   * The city of the company's address
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * The zip of the company's address
   * @member {String} zip
   */
  exports.prototype['zip'] = undefined;
  /**
   * The street of the company's address
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * The house number of the company's address
   * @member {String} house_number
   */
  exports.prototype['house_number'] = undefined;
  /**
   * The company's D-U-N-S number
   * @member {String} duns_number
   */
  exports.prototype['duns_number'] = undefined;
  /**
   * Optional the D-U-N-S number of the company's headquarters if this isn't the headquarter
   * @member {String} duns_number_hq
   */
  exports.prototype['duns_number_hq'] = undefined;
  /**
   * The company's phone number
   * @member {String} phone_number
   */
  exports.prototype['phone_number'] = undefined;
  /**
   * One-letter code describing the company's branch: **B**: branch, **N**: not a branch, **H**: headquarter, **S**: single location 
   * @member {module:Datamill/Datamill/BusinessDataDunsSearchResult.BranchCodeEnum} branch_code
   */
  exports.prototype['branch_code'] = undefined;
  /**
   * Description of the company's branch
   * @member {module:Datamill/Datamill/BusinessDataDunsSearchResult.BranchDescriptionEnum} branch_description
   */
  exports.prototype['branch_description'] = undefined;
  /**
   * Internal ranking for all results compared with each other. the value is normalized between **0** and **1** (**1** is the best matching result and **0** the least one)
   * @member {Number} score
   */
  exports.prototype['score'] = undefined;


  /**
   * Allowed values for the <code>branch_code</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BranchCodeEnum = {
    /**
     * value: "B"
     * @const
     */
    "B": "B",
    /**
     * value: "N"
     * @const
     */
    "N": "N",
    /**
     * value: "H"
     * @const
     */
    "H": "H",
    /**
     * value: "S"
     * @const
     */
    "S": "S"  };

  /**
   * Allowed values for the <code>branch_description</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BranchDescriptionEnum = {
    /**
     * value: "branch"
     * @const
     */
    "branch": "branch",
    /**
     * value: "not a branch"
     * @const
     */
    "not a branch": "not a branch",
    /**
     * value: "headquarter"
     * @const
     */
    "headquarter": "headquarter",
    /**
     * value: "single location"
     * @const
     */
    "single location": "single location"  };


  return exports;
}));


