/**
 * /data.mill for applications
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market. 
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Datamill/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.datamill-js-client) {
      root.datamill-js-client = {};
    }
    root.datamill-js-client.PhoneMobileCheckResponse = factory(root.datamill-js-client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PhoneMobileCheckResponse model module.
   * @module Datamill/Datamill/PhoneMobileCheckResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PhoneMobileCheckResponse</code>.
   * Response of successful transformation request for /phone/mobile/check
   * @alias module:Datamill/Datamill/PhoneMobileCheckResponse
   * @class
   * @param phonenumber {String} Phone number formatted to the canonical form if valid
   * @param status {module:Datamill/Datamill/PhoneMobileCheckResponse.StatusEnum} Flag if the mobile phone number is either valid and active, valid but disabled (out of network coverage), has an invalid syntax /is unreachable, or not a mobile phone number type: **valid**: the mobile phone number is valid, **inactive**: the mobile phone number is valid but out of network coverage or is turned off, **invalid**: the mobile phone number is invalid or unreachable, **no mobile number**: the phone number is not a mobile phone number, **unknown**: the phone number could not be verified 
   */
  var exports = function(phonenumber, status) {
    var _this = this;

    _this['phonenumber'] = phonenumber;
    _this['status'] = status;
  };

  /**
   * Constructs a <code>PhoneMobileCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Datamill/Datamill/PhoneMobileCheckResponse} obj Optional instance to populate.
   * @return {module:Datamill/Datamill/PhoneMobileCheckResponse} The populated <code>PhoneMobileCheckResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('phonenumber')) {
        obj['phonenumber'] = ApiClient.convertToType(data['phonenumber'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * Phone number formatted to the canonical form if valid
   * @member {String} phonenumber
   */
  exports.prototype['phonenumber'] = undefined;
  /**
   * Flag if the mobile phone number is either valid and active, valid but disabled (out of network coverage), has an invalid syntax /is unreachable, or not a mobile phone number type: **valid**: the mobile phone number is valid, **inactive**: the mobile phone number is valid but out of network coverage or is turned off, **invalid**: the mobile phone number is invalid or unreachable, **no mobile number**: the phone number is not a mobile phone number, **unknown**: the phone number could not be verified 
   * @member {module:Datamill/Datamill/PhoneMobileCheckResponse.StatusEnum} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "valid"
     * @const
     */
    "valid": "valid",
    /**
     * value: "invalid"
     * @const
     */
    "invalid": "invalid",
    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown",
    /**
     * value: "no mobile number"
     * @const
     */
    "no mobile number": "no mobile number"  };


  return exports;
}));


