/**
 * /data.mill for applications
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Datamill/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.datamill-js-client) {
      root.datamill-js-client = {};
    }
    root.datamill-js-client.SocialMediaActivitiesGetInstagram = factory(root.datamill-js-client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SocialMediaActivitiesGetInstagram model module.
   * @module Datamill/Datamill/SocialMediaActivitiesGetInstagram
   * @version 1.6.5
   */

  /**
   * Constructs a new <code>SocialMediaActivitiesGetInstagram</code>.
   * Instagram information for /social-media/activities/get
   * @alias module:Datamill/Datamill/SocialMediaActivitiesGetInstagram
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>SocialMediaActivitiesGetInstagram</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Datamill/Datamill/SocialMediaActivitiesGetInstagram} obj Optional instance to populate.
   * @return {module:Datamill/Datamill/SocialMediaActivitiesGetInstagram} The populated <code>SocialMediaActivitiesGetInstagram</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('bio')) {
        obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
      }
      if (data.hasOwnProperty('followers')) {
        obj['followers'] = ApiClient.convertToType(data['followers'], 'Number');
      }
      if (data.hasOwnProperty('is_private')) {
        obj['is_private'] = ApiClient.convertToType(data['is_private'], 'Number');
      }
      if (data.hasOwnProperty('posts')) {
        obj['posts'] = ApiClient.convertToType(data['posts'], 'Number');
      }
      if (data.hasOwnProperty('engagement')) {
        obj['engagement'] = ApiClient.convertToType(data['engagement'], 'Number');
      }
      if (data.hasOwnProperty('engagement_percent')) {
        obj['engagement_percent'] = ApiClient.convertToType(data['engagement_percent'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The fully qualified url to the person's profile
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * The person's biography written on Instagram
   * @member {String} bio
   */
  exports.prototype['bio'] = undefined;
  /**
   * The number of followers on Instagram
   * @member {Number} followers
   */
  exports.prototype['followers'] = undefined;
  /**
   * Flag if the profile is in private mode (1) or published (0)
   * @member {module:Datamill/Datamill/SocialMediaActivitiesGetInstagram.IsPrivateEnum} is_private
   */
  exports.prototype['is_private'] = undefined;
  /**
   * The number of posts on Instagram
   * @member {Number} posts
   */
  exports.prototype['posts'] = undefined;
  /**
   * The number of engagements (likes) on Instagram
   * @member {Number} engagement
   */
  exports.prototype['engagement'] = undefined;
  /**
   * The percentage of engagements (likes) relative to the number of followers on Instagram
   * @member {Number} engagement_percent
   */
  exports.prototype['engagement_percent'] = undefined;


  /**
   * Allowed values for the <code>is_private</code> property.
   * @enum {Number}
   * @readonly
   */
  exports.IsPrivateEnum = {
    /**
     * value: 0
     * @const
     */
    "0": 0,
    /**
     * value: 1
     * @const
     */
    "1": 1  };


  return exports;
}));


